### PR TITLE
Ayush/refactor

### PR DESCRIPTION
**Pull request by ayush-goyal**
Changes
----
It might be easier to review the changes by commit, since the changes are organized better.
To merge after #136 

- Refactor some of the backend code into multiple files/folders
- Switch Knex to Prisma and update all the queries and variable names and types
- A lot of the changes on the frontend are simply naming changes
- Switch npm to yarn (since prisma works weird with npm it was easier to do)

### CODE REVIEW

**Review by rahulrajus — APPROVED** [review]

**Review by evan10s — CHANGES_REQUESTED** [review]
Code changes look good but would like to see a functioning dev deployment to validate functionality

**Comment by ayush-goyal** [comment]
Ok I added a dev deployment at bolt.dev.hack.gt with Prisma. Check it out and let me know if everything is working for you. I can also make you an admin if needed. @evan10s

**Comment by evan10s** [comment]
Cool, will check it out this week

**Comment by evan10s** [comment]
I tested out the dev deployment.  Just noticed one weird thing:

- On the users page, changing a user's admin status causes the whole users table to flash
  - However, the user admin status change button is poorly implemented (read: I barely knew React at the time) so it could honestly just use a separate refactoring

I'm just going to make an issue for that; otherwise, this all seems fine to me.

**Comment by ayush-goyal** [comment]
Cool! Will you go ahead and approve the PR?

**Review by evan10s — APPROVED** [review]

**Pull request merged**
